name: Storybook preview deploy

on:
  pull_request:
    types: [labeled, synchronize, closed]

jobs:
  Preview-Deploy:
    if: ${{ contains(toJson(github.event.pull_request.labels), '[Preview] Storybook') && github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Enable node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn install

      - name: Build storybook
        run: yarn build-storybook

      - name: Rename storybook-static folder
        run: |
          mv storybook-static pr_${{github.event.pull_request.number}}

      - id: upload-files
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          path: ./pr_${{github.event.pull_request.number}}
          destination: storybook-preview

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: |
            Hi there :wave:
            I've prepared a preview of the Storybook.
            The URL will be invalidated when this PR is closed. :smile:

            https://storage.googleapis.com/storybook-preview/pr_${{github.event.pull_request.number}}/index.html
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Clean-Up:
    if: ${{ contains(toJson(github.event.pull_request.labels), '[Preview] Storybook') && github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Delete storybook preview bucket
        run: gsutil rm -r gs://storybook-preview/pr_${{github.event.pull_request.number}}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: |
            âœ… Clean up was successful.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
